login_app/urls.py
from django.urls import path
from login_app import views

app_name='login_app'

urlpatterns = [
    path('' ,views.index, name='index')
    
]

my_second_project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('login_app.urls'))
    
]

login_app/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class UserInfo(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    facebook_id=models.URLField()
    profile_pic=models.ImageField(upload_to='profile_pics',blank=True)
    
    def __str__(self):
        return self.user.username

login_app/forms.py
from django import forms
from django.contrib.auth.models import User
from login_app.models import UserInfo

class UserForm(forms.ModelForm):
    class Meta():
        model=User
        fields=('username','email','password',)
        
class UserInfoForm(forms.ModelForm):
    class Meta():
        model=UserInfo
        fields=('facebook_id','profile_pic',)
    

login_app/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    diction={}
    return render(request, 'login_app/index.html',context=diction)

templates/login_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <title>{{title}}</title>
</head>
<body>

    <nav class="navbar navbar-expand-lg bg-body-tertiary">
        <div class="container-fluid">
          <a class="navbar-brand" href="#">Navbar</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'login_app:index' %}">Home</a>
              </li>
            </ul>
          </div>
        </div>
      </nav>
    <div class="container">
         {% block body_block  %}
               
         {% endblock  %}


    </div>
    

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>

</body>
</html>

templates/login_app/index.html
{% extends "login_app/base.html" %}
{% block body_block %}
  <h3>Index Page</h3>
{% endblock  %}